### ISSUE TITLE
Issue with align() function

### ISSUE THREAD

**Issue by sartaj10** [esnet/pypond#17]
`data = dict(
              name="traffic",
              columns=["time", "value"],
              points=[
                  [1473490769000, 10],
                  [1473490799000, 20],
                  [1473490829000, 30],
                  [1473490850000, 40]
              ]
          )`

`base_30_sec = (
             Pipeline()
             .from_source(TimeSeries(data))
             .align(window = '30s', method = 'linear', limit = 10)
             .to_keyed_collections()
         )`

`print base_30_sec.get('all')`

Output is 
`[{"data": {"value": 10.333333333333334}, "time": 1473490770000}, {"data": {"value": 20.333333333333332}, "time": 1473490800000}, {"data": {"value": 30.476190476190474}, "time": 1473490830000}]`

There's no data for the aligned [1473490850000, 40] timestamp

**Comment by montegoode** [comment]
Actually, there is.

```
ts=2016-09-15 07:04:25,029 event=Align.add_event id=1473948265 incoming: {"data": {"value": 40}, "time": 1473490850000}
ts=2016-09-15 07:04:25,029 event=Align.add_event id=1473948265 boundary: 30s-49116361
ts=2016-09-15 07:04:25,029 event=Align.add_event id=1473948265 emitting: {"data": {"value": 30.476190476190474}, "time": 1473490830000}
```
This is working as intended.

- The first point (value=10) does not land on a window boundary so it is not emitted, but saved internally.
- The second point (value=20) lies "across" the window boundary from the first point, so the first (value=10.33) output value is the first aligned value which is generated from point 1 and point 2.
- The third point (value=30) lies across the boundary from the second point, so the second (value=20.33) aligned value is emitted.
- The fourth point (value=40) lies across the boundary from the third point and results in the final aligned point to be emitted, etc etc etc.

The aligner will not necessarily emit the same number of points that it is fed. The **only** case where the first point will cause an event to be emitted is if it lies exactly on a window boundary. Otherwise the first event is just "held." 

In the case of larger gaps between two points spanning multiple window boundaries, this will result in multiple points being generated between the two incoming points. In the case of multiple events being clustered in the same window (aligned events are only emitted when a boundary is crossed between two points) it could emit fewer events than the input.
