### ISSUE TITLE
Rollups force non-UTC times?

### ISSUE THREAD

**Issue by jdugan1024** [esnet/pypond#22]
For `TimeSeries.yearly_rollup`, `TimeSeries.daily_rollup`, and `TimeSeries.monthly_rollup` the call to `_rollup` forces utc to False.  For example:

https://github.com/esnet/pypond/blob/master/pypond/series.py#L1373

Although, `TimeSeries.daily_rollup` does not.  

At a minimum these should be consistent.  Also, it seems like they should default to UTC and have a kwarg to allow you to override that if you want.  Is this an oversight or some design decision I don't grok?

This behavior was very confusing when I was using pypond to make monthly rollups today. I ended up using `_rollup` to get around it for now.

**Comment by montegoode** [comment]
I see there was discussion of the issue on slack while I was out and @pjm17971 outlined how the rollups were defaulting to a client-side representation. So @jdugan1024 can you give me a use case/json/code snippet and let me see what your requirements are? It appears that we need some additional flags but I'm not quite able to tease what we need out of the exchange on slack.

**Comment by pjm17971** [comment]
The summary from slack is:

 - *Fixed window* rollups are designed to always be UTC. They are intended for things like 5m rollups. These are the same regardless of timezone. There's no current requirement for larger rollups (e.g. 7d) to account for local vs utc offsets. If you are rolling up like that, you are probably not on the client.
 - *Daily*, *monthly*, (and eventually weekly) rollups default to local time. This is @jdugan1024's primary issue, but it is intentional. They default to this because of doing this on the client. I'm willing to say this can be reconsidered such that the default should be UTC in all cases. However, just stating what the difference is: If you visualize a UTC window locally, it will be confusing to the user. We do, however, support UTC time axis now in the charts code (and soon all timezones), so that can be mitigated. However, there's still cases in which you want client-side visualization to be in local time. I'd argue that this is mostly the case. However, we can change the default here (though it would be an unfortunately breaking change for anyone using that functionality).
 - To achieve the ability to specify that a daily or monthly rollup in either local or UTC time (or any timezone would be nice), we probably have to add a new state to the pipeline and then apply that in the aggregation processor code. Essentially it sets a flag in the IndexEvent generation so as to fully define which day, month, year is meant (local or utc), and therefore what events are in which index.

**Comment by jdugan1024** [comment]
With my initial comments I didn't know there was a reason that things defaulted to local time. It would be nice if the docstring had a brief explanation so others don't get confused as well. Since there is a good reason for it I'm fine with leaving the default behavior as is.  

When I pointed it out it my solution seemed obvious because the pypond docs push pretty hard towards UTC (http://software.es.net/pypond/time.html#utc-vs-local-time: "When passing in a datetime object, it is encouraged that they be in UTC as well.") So I thought I was just helping with consistency from that point of view.  Anyway, probably best to just leave the default alone and document the reasoning?

I think the main thing I was hoping for is a kwarg to allow me use UTC or another timezone if possible.  I'll be happy with just this and leaving the defaults as-is.

**Comment by montegoode** [comment]
There is this in the docstrings of all of those functions:

```
        This helper function renders the aggregations in localtime. If you
        want to render in UTC use .fixed_window_rollup() with the appropriate
        window size.
```

Does `fixed_window_rollup()` not fill the bill? 

But sure, I can add a boolean flag to those functions to make them render in UTC if need be. Kind of feels like the default should be left as-is however.

**Comment by montegoode** [comment]
Updated docstrings for greater clarity: https://github.com/esnet/pypond/commit/75db5b79265cbe7e091b5ea15d8824ece35bb7b6

Added new booleans options to allow for rolling up in UTC: https://github.com/esnet/pypond/commit/0bc8410aa8db30cff5eb4db48b57ef9ce7105ec2
